# Analysis options for Kap-App Flutter Frontend
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "lib/l10n/*.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    todo: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
