name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    name: Go Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Get dependencies
        working-directory: ./kap-app-backend
        run: go mod download

      - name: Run Go Tests
        working-directory: ./kap-app-backend
        run: go test -v ./...

  frontend-tests:
    name: Flutter Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        working-directory: ./kap-app-front
        run: flutter pub get

      - name: Run Flutter Analyze
        working-directory: ./kap-app-front
        run: flutter analyze

      - name: Run Flutter Tests
        working-directory: ./kap-app-front
        run: flutter test
